# Generated by Django 4.2 on 2024-07-23 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HouseInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=8, null=True)),
                ("title", models.CharField(blank=True, max_length=56, null=True)),
                ("region", models.CharField(blank=True, max_length=16, null=True)),
                ("area", models.CharField(blank=True, max_length=8, null=True)),
                ("house_type", models.CharField(blank=True, max_length=8, null=True)),
                ("house_size", models.CharField(blank=True, max_length=16, null=True)),
                ("toward", models.CharField(blank=True, max_length=16, null=True)),
                ("decoration", models.CharField(blank=True, max_length=8, null=True)),
                ("floor", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "building_type",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("year", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "view_field",
                    models.CharField(
                        blank=True, db_column="view_", max_length=8, null=True
                    ),
                ),
                (
                    "release_time",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("single_price", models.CharField(blank=True, max_length=8, null=True)),
                ("total_price", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "houseInfo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "uuid",
                    models.UUIDField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(blank=True, max_length=16, null=True)),
                ("nick_name", models.CharField(max_length=16)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("sex", models.BooleanField(default=True)),
                ("phone", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=254)),
                ("born", models.DateField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=32, null=True)),
                ("time", models.DateTimeField(auto_now_add=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatar"),
                ),
            ],
            options={
                "db_table": "userInfo",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=32, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=32)),
                (
                    "role",
                    models.CharField(
                        choices=[(0, "普通用户"), (1, "会员用户"), (2, "管理员")],
                        default="普通用户",
                        max_length=16,
                    ),
                ),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "userInfo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.userinfo",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
