# Generated by Django 4.2 on 2026-01-27 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HousePricePrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_features", models.JSONField(verbose_name="预测输入特征")),
                ("predicted_price", models.IntegerField(verbose_name="预测总价(元)")),
                (
                    "predict_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="预测时间"),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.houseinfo",
                        verbose_name="关联房源",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "房价预测记录",
                "verbose_name_plural": "房价预测记录",
                "db_table": "house_price_prediction",
            },
        ),
    ]
